set_property SRC_FILE_INFO {cfile:/home/henrique/Documentos/projeto-circuitos-reconfiguraveis/Exercicios/henrique_gmoura_160058651/Exercicio_1/trem/trem.srcs/constrs_1/imports/trem/Basys3_Master.xdc rfile:../../../trem.srcs/constrs_1/imports/trem/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
