#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Sep 13 11:15:58 -03 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_project_1_voto_ABC_behav -key {Behavioral:sim_1:Functional:tb_project_1_voto_ABC} -tclbatch tb_project_1_voto_ABC.tcl -view /home/henrique/Documentos/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/tb_project_1_voto_ABC_behav.wcfg -log simulate.log
