set_property SRC_FILE_INFO {cfile:/home/henrique/Documentos/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/project_1_voto_ABC.srcs/constrs_1/imports/project_1_voto_ABC/Basys3_Master.xdc rfile:../../../project_1_voto_ABC.srcs/constrs_1/imports/project_1_voto_ABC/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led}]
