webtalk_init -webtalk_dir C:/Users/Alunos/Documents/HGM/PCR/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/project_1_voto_ABC.sim/sim_1/behav/xsim/xsim.dir/tb_project_1_voto_ABC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 11 09:17:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "99a3a961-0c17-4b2d-925d-f750b8806b3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6742a92c824b4259acc63ec0e95f841a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3 CPU       M 390  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2660 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6452_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2949140241 -regid "" -xml C:/Users/Alunos/Documents/HGM/PCR/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/project_1_voto_ABC.sim/sim_1/behav/xsim/xsim.dir/tb_project_1_voto_ABC_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Alunos/Documents/HGM/PCR/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/project_1_voto_ABC.sim/sim_1/behav/xsim/xsim.dir/tb_project_1_voto_ABC_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Alunos/Documents/HGM/PCR/projeto-circuitos-reconfiguraveis/Exercicios/Combinacional/project_1_voto_ABC/project_1_voto_ABC.sim/sim_1/behav/xsim/xsim.dir/tb_project_1_voto_ABC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
